---
apiVersion: v1
kind: ConfigMap
metadata:
  name: guacamole-config
  namespace: guacamole-ns
data:
  guacamole.properties: |
    # Hostname and port of guacd
    guacd-hostname: guacd-service.guacamole-ns.svc.cluster.local
    guacd-port: 4822

    # MySQL properties
    mysql-hostname: ext-mariadb.guacamole-ns.svc.cluster.local
    mysql-port: 3306
    mysql-database: guacamole
    mysql-username: guacamole
    mysql-password: guacamole
