require("config.lazy")
require("config.workspaces")
require("config.sess")
require("config.treesitter")
require("config.tele")
require("config.dap")
require("config.neovim")
require("config.autocmd")
