name: n8n

services:
  n8n:
    image: oonray/comfy:latest
    environment:
      PUID: "$${PUID: -999}"
      PGID: "$${PGID: -999}"
      GENERIC_TIMEZONE: "UTC+1"
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: true
      N8N_RUNNERS_ENABLED: true
    ports:
      - "5678:5678"
    restart: unless-stopped
    volumes:
      - type: volume
        source: docker
        target: /home/node/.n8n
        volume:
          subpath: n8n
