name: ollama

services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main-slim
    ports:
      - "8288:3000"
    volumes:
      - type: volume
        source: ai_path
        target: /app/backend/data
        volume:
          subpath: openwebui
    environment:
        OLLAMA_BASE_URL: https://ollama:11434
  ollama:
    image: ollama/ollama:latest
      #ports:
      #- "11434:11434"
    restart: unless-stopped
    volumes:
      - type: volume
        source: ai_path
        target: /root/.ollama
        volume:
          subpath: ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
