name: ollama

services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    restart: unless-stopped
    volumes:
      - type: volume
        source: ai_path
        target: /root/.ollama
        volume:
          subpath: ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    restart: always
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    ports:
      - "8288:8080"
    volumes:
      - type: volume
        source: ai_path
        target: /app/backend/data
        volume:
          subpath: openwebui
