name: Build Container

on:
  workflow_call:
    inputs:
      args:
        type: string
      image:
        required: true
        type: string
      base:
        required: true
        type: string
      tag:
        required: true
        type: string
      context:
        required: true
        type: string
    secrets:
      username:
          required: true
      password:
          required: true

jobs:
  build-image:
    runs-on: debian-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

    # - name: Login to Docker ghcr
    #   uses: docker/login-action@v3
    #   with:
    #     registry: ghcr.io
    #     username: ${{ secrets.username }}
    #     password: ${{ secrets.password }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
      - name: Build and push ${{ inputs.image }} ${{ inputs.arch }}
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          build-args: |
            ${{ inputs.args }}
          build-contexts: |
            base=docker-image://${{ inputs.base }}
          context: ${{ inputs.context }}
          push: true
          tags: |
            oonray/${{ inputs.image }}:${{ inputs.tag }}
            oonray/${{ inputs.image }}:latest
    #       ghcr.io/oonray/${{ inputs.image }}:${{ inputs.tag }}
    #       ghcr.io/oonray/${{ inputs.image }}:latest
