name: Docker image evilginx

on:
  push:
    paths:
      - 'evilginx/*'
      - 'evilginx/**'
      - 'base/dev/go/*'
      - 'base/dev/go/**'
      - 'base/dev/node/*'
      - 'base/dev/node/**'
jobs:
  build-evilginx-go:
    uses: oonray/Containers/.github/workflows/container.yml@main
    with:
      image: evilginx
      tag: golang
      base: oonray/user-evilginx:latest
      context: base/dev/go
    secrets:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}


  build-evilginx-node:
    uses: oonray/Containers/.github/workflows/container.yml@main
    needs: build-evilginx-go
    with:
      image: evilginx
      tag: node
      base: oonray/evilginx:golang
      context: base/dev/node
    secrets:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}

  build-evilginx:
    uses: oonray/Containers/.github/workflows/container.yml@main
    needs: build-evilginx-node
    with:
      image: evilginx
      tag: v1.0.0
      base: oonray/evilginx:node
      context: evilginx
    secrets:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}
