name: Docker image Install

on:
  push:
    paths:
      - 'base/install/*'
      - 'base/install/**'

jobs:
  build-kali-amd64:
    uses: oonray/Containers/.github/workflows/container.yml@main
    with: 
      arch: amd64
      image: kali
      tag: install
      platform: linux/amd64
      base: kalilinux/kali-rolling:amd64
      context: base/install

  build-kali-arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push kali install arm64
        uses: docker/build-push-action@v6
        with:
          platform: linux/arm64
          build-args: |
            ARCH=arm64
          build-contexts: |
            base=docker-image://kalilinux/kali-rolling:arm64
          context: base/install
          push: true
          tags: oonray/kali:install

  build-debian-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push debian install amd64
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          build-args: |
            ARCH=amd64
          build-contexts: |
            base=docker-image://debian:latest
          context: base/install
          push: true
          tags: oonray/debian:install

  build-debian-arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push debian install arm64
        uses: docker/build-push-action@v6
        with:
          platforms: linux/arm64
          build-args: |
            ARCH=arm64
          build-contexts: |
            base=docker-image://debian:latest
          context: base/install
          push: true
          tags: oonray/debian:install
