name: Docker image Install

on:
  push:
    paths:
      - '.github/workflows/install.yml'
      - '.github/workflows/container.yml'
      - 'base/install/*'
      - 'base/install/**'

jobs:
  build-install-kali-amd64:
    uses: oonray/Containers/.github/workflows/container.yml@main
    with:
      arch: amd64
      image: kali
      tag: install
      platform: linux/amd64
      base: kalilinux/kali-rolling:amd64
      context: base/install
    secrets:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}

  build-install-kali-arm64:
    uses: oonray/Containers/.github/workflows/container.yml@main
    with:
      arch: arm64
      image: kali
      tag: install-arm64
      platform: linux/arm64
      base: kalilinux/kali-rolling:arm64
      context: base/install
    secrets:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}

  build-install-debian-amd64:
    uses: oonray/Containers/.github/workflows/container.yml@main
    with:
      arch: amd64
      image: debian
      tag: install
      platform: linux/amd64
      base: debian:latest
      context: base/install
    secrets:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}

  build-install-debian-arm64:
    uses: oonray/Containers/.github/workflows/container.yml@main
    with:
      arch: arm64
      image: debian
      tag: install-arm64
      platform: linux/arm64
      base: debian:latest
      context: base/install
    secrets:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}
