name: Docker image kali

on:
  push:
    paths:
      - 'kali/*'
      - 'kali/**'

jobs:
  build-kali-base:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push kali amd64
        uses: docker/build-push-action@v6
        with:
          context: base/kali
          push: true
          tags: oonray/kali:base-amd64
      - name: Build and push kali amd64
        uses: docker/build-push-action@v6
        with:
          build-args: ARCH=arm64
          context: base/kali
          push: true
          tags: oonray/kali:base-arm64
  build-kali:
    needs: build-kali-base
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push kali
        uses: docker/build-push-action@v6
        with:
          context: kali
          push: true
          tags: oonray/kali:latest
      - name: Build and push kali amd64
        uses: docker/build-push-action@v6
        with:
          context: kali
          push: true
          tags: oonray/kali:amd64
      - name: Build and push kali arm64
        uses: docker/build-push-action@v6
        with:
          build-args: ARCH=arm64
          context: kali
          push: true
          tags: oonray/kali:arm64
