name: Docker image kali

on:
  push:
    paths:
      - 'kali/*'
      - 'kali/**'
jobs:
  build-kali-amd64:
    uses: oonray/Containers/.github/workflows/container.yml@main
    with:
      image: kali
      tag: v1.0.0
      base: oonray/user-kali:latest
      context: kali
    secrets:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}
