name: Docker image user

on:
  push:
    paths:
      - '.github/workflows/user.yml'
      - '.github/workflows/container.yml'
      - 'base/user/*'
      - 'base/user/**'

jobs:
  build-kali-amd64:
    uses: oonray/Containers/.github/workflows/container.yml@main
    with:
      arch: amd64
      image: kali
      tag: install
      platform: linux/amd64
      base: oonray/kali:install
      context: base/user
      args: |
        USR=kali
    secrets:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}

  build-kali-arm64:
    uses: oonray/Containers/.github/workflows/container.yml@main
    with:
      arch: arm64
      image: kali
      tag: install
      platform: linux/arm64
      base: oonray/kali:install-arm64
      context: base/user
      args: |
        USR=kali
    secrets:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}

  build-debian-amd64:
    uses: oonray/Containers/.github/workflows/container.yml@main
    with:
      arch: amd64
      image: debian
      tag: install
      platform: linux/amd64
      base: oonray/debian:install
      context: base/user
      args: |
        USR=kali
    secrets:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}

  build-debian-arm64:
    uses: oonray/Containers/.github/workflows/container.yml@main
    with:
      arch: arm64
      image: debian
      tag: install
      platform: linux/arm64
      base: oonray/debian:install-arm64
      context: base/user
      args: |
        USR=kali
    secrets:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}
