name: Docker image user

on:
  push:
    paths:
      - 'base/user/*'
      - 'base/user/**'

jobs:
  build-user-kali:
    uses: oonray/Containers/.github/workflows/container.yml@main
    with:
      image: user-kali
      tag: v1.0.0
      base: oonray/base-kali:latest
      context: base/user
      args: |
        USR=kali
    secrets:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}

  build-user-debian:
    uses: oonray/Containers/.github/workflows/container.yml@main
    with:
      image: user-debian
      tag: v1.0.0
      platform: linux/amd64
      base: oonray/base-debian:latest
      context: base/user
    secrets:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}

  build-user-evilginx:
    uses: oonray/Containers/.github/workflows/container.yml@main
    with:
      image: user-evilginx
      tag: v1.0.0
      base: oonray/base-debian:latest
      context: base/user
      args: |
        USR=evilginx
    secrets:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}

  build-user-c2:
    uses: oonray/Containers/.github/workflows/container.yml@main
    with:
      image: user-c2
      tag: v1.0.0
      base: oonray/base-debian:latest
      context: base/user
      args: |
        USR=sliver
    secrets:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}

