name: Docker image user

on:
  push:
    paths:
      - 'base/user/*'
      - 'base/user/**'

jobs:
  build-user-kali-amd64:
    uses: oonray/Containers/.github/workflows/container.yml@main
    with:
      arch: amd64
      image: kali
      tag: user
      platform: linux/amd64
      base: oonray/kali:install
      context: base/user
      args: |
        USR=kali
    secrets:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}

  build-user-kali-arm64:
    uses: oonray/Containers/.github/workflows/container.yml@main
    with:
      arch: arm64
      image: kali
      tag: user-arm64
      platform: linux/arm64
      base: oonray/kali:install-arm64
      context: base/user
      args: |
        USR=kali
    secrets:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}

  build-user-debian-amd64:
    uses: oonray/Containers/.github/workflows/container.yml@main
    with:
      arch: amd64
      image: debian
      tag: user
      platform: linux/amd64
      base: oonray/debian:install
      context: base/user
    secrets:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}

  build-user-debian-arm64:
    uses: oonray/Containers/.github/workflows/container.yml@main
    with:
      arch: arm64
      image: debian
      tag: user-arm64
      platform: linux/arm64
      base: oonray/debian:install-arm64
      context: base/user
    secrets:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}

  build-user-evilginx-amd64:
    uses: oonray/Containers/.github/workflows/container.yml@main
    with:
      arch: amd64
      image: evilginx
      tag: user
      platform: linux/amd64
      base: oonray/debian:install
      context: base/user
      args: |
        USR=evilginx
    secrets:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}

  build-user-evilginx-arm64:
    uses: oonray/Containers/.github/workflows/container.yml@main
    with:
      arch: arm64
      image: evilginx
      tag: user
      platform: linux/arm64
      base: oonray/debian:install-arm64
      context: base/user
      args: |
        USR=evilginx
    secrets:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}

  build-user-c2-amd64:
    uses: oonray/Containers/.github/workflows/container.yml@main
    with:
      arch: amd64
      image: c2
      tag: user
      platform: linux/amd64
      base: oonray/debian:install
      context: base/user
      args: |
        USR=sliver
    secrets:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}

  build-user-c2-arm64:
    uses: oonray/Containers/.github/workflows/container.yml@main
    with:
      arch: arm64
      image: c2
      tag: user
      platform: linux/arm64
      base: oonray/debian:install-arm64
      context: base/user
      args: |
        USR=sliver
    secrets:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}
