name: Docker image VPN
#VPN
on:
  push:
    paths:
      - '.github/workflows/vpn-image.yml'
      - 'vpn/*'
      - 'vpn/**'

jobs:
  build_dev:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push dev
        uses: docker/build-push-action@v6
        with:
          context: vpn
          push: true
          tags: oonray/vpn:latest
